### ISSUE TITLE
Selecting an option

### ISSUE THREAD

**Issue by ThePortalDAO** [ldrahnik/asus-stylus-driver#2]
How do i select an option on fedora terminal?

![Screenshot from 2022-07-25 01-40-19](https://user-images.githubusercontent.com/107817695/180668875-3fe48734-8f41-471a-88f3-881cc1ac9440.png)

**Comment by ldrahnik** [comment]
@ThePortalDAO Is fixed now. My bad.

**Comment by ThePortalDAO** [comment]
How do I select? It still doesn't select when I type in 1?

**Comment by ldrahnik** [comment]
Yes, with `1`. Did you `git pull`?

**Comment by ThePortalDAO** [comment]
No should I do instead of git clone?
What would be the full code now? How do I git pull?

**Comment by ldrahnik** [comment]
Few mins later when you reported issue I `git push` 'ed fix. So you can do a `git pull` in root of project where is `.git` folder (what I recommend!) or the same result has removing entire directory with project and do again `git clone` (which I do not recommend because why download entire project again when is possible download only last change/fix).

**Comment by ThePortalDAO** [comment]
Thank you!!!

**Comment by ldrahnik** [comment]
If you find the project useful, do not forget to give a project a star.
If you will face another issue or have knowledge from using Asus pen, feel free to participate again.
