### ISSUE TITLE
Click delay

### ISSUE THREAD

**Issue by BSalem** [ldrahnik/asus-stylus-driver#8]
Everything with the Pen touch and Pressure works pretty good and as expected, except that the when clicking using the pen, the click doesn't work until holding the pen tip touching the screen for some milliseconds, then it works smooth.

For example: to drag a window, if you click and drag, it won't work, but if you click, keep it clicked for a while then start dragging, then it works smoothly

Accordingly:
1. double click is impossible, since each click has to have long time of hold before it's recognized as a click.
2. Single click doesn't work (until holding it clicked for a while)
3. Painting a stroke, will start working smoothly after dragging for some distance and when the click starts to get recognized.

Notes:
1. This issue is only with the pen tip (other pen buttons works immediately when pressed)
2. There is no issue with the Pen itself, and it works as expected on windows.

**Comment by ldrahnik** [comment]
@BSalem Hello! Thank you for creating an issue. Unfortunately, I do not have my stylus device atm to test this weird behavior. I hope I will be able to react soon.

**Comment by ldrahnik** [comment]
@BSalem I tested what you described but I do not have this problem, it works for me just fine compared to Windows (I have dual boot Windows 11). So I am closing this issue as not related to this driver, the issue has to be reported in the original driver, and I am closing the issue because I do not have even a way how to replicate this problem
